Fix dieharder build. (#5)
* Fix static build with configure --disable-shared.

The verbose global is definen in libdieharder/parse.c
and as extern in libdieharder.h.

Globals shoudl not define it again, as compilation fails
with configure --disable-shared:
/usr/bin/ld: dieharder/libdieharder/parse.c:15:
multiple definition of `verbose';

* Fix parallel build of dieharder.

The dieharder binary depends on libdieharder, with paralle
 make -jX it can happen that it is not yet built.
make[1]: *** No rule to make target '../libdieharder/libdieharder.la',
needed by 'dieharder'.  Stop.

Just make library as dependence of program on the top
level Makefile.